import { useEffect, useState, type FormEvent } from 'react';
import type { ConfigurationSnapshot, ConfigurationValues, DroneProject } from '../../../../src/domain/types';
import { parseConfiguration, compareConfigurations } from '../../../../src/domain/configuration';
import { Icon } from '../icons';
import { Empty, Panel, Tag, dateTime, firmwareName, messageOf } from './common';

export function ConfigurationView({ project, snapshots, native, busy, onSave, onProjects }: { project?: DroneProject; snapshots: ConfigurationSnapshot[]; native: boolean; busy: boolean; onSave: (label: string, values: ConfigurationValues) => Promise<void>; onProjects: () => void }) {
  const [label, setLabel] = useState(''); const [json, setJson] = useState('{}'); const [error, setError] = useState('');
  const [selectedId, setSelectedId] = useState(''); const [compareId, setCompareId] = useState('');
  useEffect(() => { setLabel(''); setJson('{}'); setSelectedId(''); setCompareId(''); setError(''); }, [project?.id]);
  const selected = snapshots.find(snapshot => snapshot.id === selectedId);
  const comparison = snapshots.find(snapshot => snapshot.id === compareId);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError('');
    try { const values = parseConfiguration(json); await onSave(label.trim(), values); }
    catch (err) { setError(messageOf(err)); }
  };
  if (!project) return <Panel title="Configuration snapshots"><Empty icon="configure" title="Select an airframe to configure" action={<button className="button secondary" onClick={onProjects}>Open projects<Icon name="arrow" size={16} /></button>}>Snapshots belong to a project. Create or select a drone to begin recording local configuration revisions.</Empty></Panel>;
  return <><div className="context-strip"><span className="project-symbol"><Icon name={project.kind === 'physical' ? 'drone' : 'simulation'} size={21} /></span><div><strong>{project.name}</strong><span>{firmwareName(project.firmware)} · {project.kind}</span></div><Tag tone="green">LOCAL CONFIGURATION</Tag></div><div className="configuration-grid"><Panel title="Create a snapshot" eyebrow="LOCAL PROJECT DATA"><form className="snapshot-form" onSubmit={submit}><label className="field">Snapshot label<input required value={label} maxLength={100} onChange={event => setLabel(event.target.value)} placeholder="e.g. Initial airframe configuration" /></label><label className="field">Configuration JSON<textarea className="code-editor" spellCheck={false} rows={13} value={json} onChange={event => setJson(event.target.value)} aria-describedby="json-help" /></label><p id="json-help" className="form-note">Enter a JSON object with string, number, or boolean values. These local values are not validated against firmware parameters.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="snapshot-actions"><span><Icon name="lock" size={14} />No hardware write</span><button className="button primary" disabled={!native || busy || !label.trim()} type="submit"><Icon name="plus" size={16} />{busy ? 'Saving…' : 'Save snapshot'}</button></div></form></Panel><Panel title="Snapshot history" eyebrow={`${snapshots.length} SAVED REVISIONS`}>{snapshots.length ? <div className="snapshot-list">{snapshots.map(snapshot => <button key={snapshot.id} className={`snapshot-row ${snapshot.id === selectedId ? 'selected' : ''}`} onClick={() => setSelectedId(snapshot.id)}><Icon name="code" size={18} /><div><strong>{snapshot.label}</strong><span>{dateTime(snapshot.createdAt)}</span></div><Icon name="chevron" size={15} /></button>)}</div> : <Empty icon="clock" title="A clean configuration history">Save your first snapshot to start tracking changes to this project.</Empty>}</Panel></div>{selected && <Panel title={selected.label} eyebrow="SAVED SNAPSHOT" className="section-gap" action={<button className="text-button" onClick={() => { setJson(JSON.stringify(selected.values, null, 2)); setLabel(`${selected.label} — edited`.slice(0, 100)); }}>Use as draft<Icon name="arrow" size={15} /></button>}><div className="snapshot-inspect"><label className="field compare-field">Compare against<select value={compareId} onChange={event => setCompareId(event.target.value)}><option value="">No comparison — show saved values</option>{snapshots.filter(snapshot => snapshot.id !== selected.id).map(snapshot => <option key={snapshot.id} value={snapshot.id}>{snapshot.label}</option>)}</select></label>{comparison && comparison.id !== selected.id ? <SnapshotDiff before={comparison.values} after={selected.values} /> : <pre className="json-preview">{JSON.stringify(selected.values, null, 2)}</pre>}</div></Panel>}</>;
}

function SnapshotDiff({ before, after }: { before: ConfigurationValues; after: ConfigurationValues }) {
  const changes = compareConfigurations(before, after);
  return changes.length ? <div className="diff-container"><p className="form-note">Changes from the comparison snapshot to the selected snapshot.</p><table className="diff-table"><thead><tr><th>Parameter</th><th>Comparison</th><th>Selected snapshot</th></tr></thead><tbody>{changes.map(change => <tr key={change.key}><th scope="row">{change.key}<span className="diff-kind">{change.kind}</span></th><td className="diff-before"><pre>{change.previous === undefined ? '? absent' : JSON.stringify(change.previous)}</pre></td><td className="diff-after"><pre>{change.next === undefined ? '? absent' : JSON.stringify(change.next)}</pre></td></tr>)}</tbody></table></div> : <div className="no-diff"><Icon name="check" size={20} /><span>These snapshots contain the same configuration values.</span></div>;
}

