import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { DroneProject } from '../../../../src/domain/types';
import { Icon } from '../icons';
import { Tag, firmwareName, messageOf } from './common';

export function ProjectList({ projects, selectedId, select, busy, limit }: { projects: DroneProject[]; selectedId?: string; select: (id: string) => void; busy: boolean; limit?: number }) {
  return <div className="project-list">{projects.slice(0, limit).map(project => <button key={project.id} className={`project-row ${project.id === selectedId ? 'selected' : ''}`} disabled={busy} onClick={() => select(project.id)} aria-pressed={project.id === selectedId}><span className="project-symbol"><Icon name={project.kind === 'physical' ? 'drone' : 'simulation'} size={23} /></span><div className="project-row-body"><strong>{project.name}</strong><p>{firmwareName(project.firmware)}<span>·</span>{project.kind}<span>·</span>Revision {project.configurationRevision}</p></div>{project.id === selectedId ? <Tag tone="green">SELECTED</Tag> : <Icon name="chevron" size={18} />}</button>)}</div>;
}

export function CreateProjectDialog({ busy, onClose, onCreate }: { busy: boolean; onClose: () => void; onCreate: (input: { name: string; description: string; kind: DroneProject['kind']; firmware: DroneProject['firmware'] }) => Promise<void> }) {
  const [name, setName] = useState(''); const [description, setDescription] = useState('');
  const [kind, setKind] = useState<DroneProject['kind']>('physical');
  const [firmware, setFirmware] = useState<DroneProject['firmware']>('betaflight');
  const [error, setError] = useState(''); const dialogRef = useRef<HTMLDialogElement>(null);
  useEffect(() => { dialogRef.current?.showModal(); return () => dialogRef.current?.close(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await onCreate({ name: name.trim(), description: description.trim(), kind, firmware }); } catch (err) { setError(messageOf(err)); } };
  return <dialog ref={dialogRef} className="project-dialog" onCancel={event => { event.preventDefault(); if (!busy) onClose(); }} aria-labelledby="create-project-title"><form onSubmit={submit}><div className="dialog-header"><div><span className="eyebrow">NEW AIRFRAME</span><h2 id="create-project-title">Create a project</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={busy} aria-label="Close project dialog"><Icon name="close" /></button></div><p className="dialog-description">Give your drone a home for its configuration and engineering history.</p><label className="field">Project name<input autoFocus required maxLength={100} placeholder="e.g. Workshop quad" value={name} onChange={event => setName(event.target.value)} /></label><fieldset className="vehicle-options"><legend>Vehicle type</legend>{(['physical', 'simulated'] as const).map(option => <label key={option} className={kind === option ? 'checked' : ''}><input type="radio" name="kind" value={option} checked={kind === option} onChange={() => setKind(option)} /><Icon name={option === 'physical' ? 'drone' : 'simulation'} size={23} /><strong>{option === 'physical' ? 'Physical drone' : 'Simulated vehicle'}</strong><span>{option === 'physical' ? 'Real flight-controller hardware' : 'A virtual engineering project'}</span></label>)}</fieldset><label className="field">Firmware ecosystem<select value={firmware} onChange={event => setFirmware(event.target.value as DroneProject['firmware'])}><option value="betaflight">Betaflight</option><option value="px4">PX4</option><option value="ardupilot">ArduPilot — future adapter</option><option value="custom">Custom firmware — future adapter</option></select></label><label className="field">Description <span className="optional">(optional)</span><textarea maxLength={2000} rows={3} value={description} onChange={event => setDescription(event.target.value)} placeholder="Airframe, purpose, or notes for this project" /></label>{error && <p className="form-error" role="alert">{error}</p>}<p className="form-note"><Icon name="info" size={15} />Creates local project metadata. No hardware is connected or configured.</p><div className="dialog-footer"><button className="button secondary" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="button primary" type="submit" disabled={busy || !name.trim()}>{busy ? 'Creating…' : 'Create project'}<Icon name="arrow" size={16} /></button></div></form></dialog>;
}

